### ISSUE TITLE
No 'Open IDE' button

### ISSUE THREAD

**Issue by hemeshvpatel** [learn-co-curriculum/programming-univbasics-2-sequence-and-comments#2]
Hi, there is currently no open IDE button for this section. I double checked that I have in browser IDE selected in my account as well.

**Comment by maxwellbenton** [comment]
Hi @vaderdoodle,

Thank you for providing feedback on this issue. We believe the issue causing the button to not appear has been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙

**Comment by ivalentine** [comment]
Hey @maxwellbenton,

It looks like this issue has not been fixed. I encountered it with another student today.
